import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { PostCard, PostWidget, Categories } from '../components';
import { getPostCards } from '../services';

export async function getStaticProps() {
  const response = await getPostCards();
  const postData = await response.posts;

  return {
    props: {
      postData
    }
  }
}

export default function Home({ postData }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>cmrib blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.postsContainer}>
        {postData.map((post) => (
          <PostCard post={post} key={post.slug} />
        ))}
      </div>

    </div>
  )
}